version: '3'

volumes:
  dbdata:

services:

  furrydb:
    container_name: furrydb
    image: mysql:8.0.17
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: nuevacontraseñafurry
      MYSQL_DATABASE: posts
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

  furryadvisor-1:
    container_name: furryadvisor-1
    image: carlosmariano05/repoprueba:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://furrydb:3306/posts
    restart: always
    depends_on:
      - furrydb
